### ISSUE TITLE
"Contains malicious files"

### ISSUE THREAD

**Issue by Master-Chiwu** [Twigonometry/Cybersecurity-Notes#1]
When downloading the repository, windows defender flags it as a trojan. So does virus total. Any reason why this is happening? 
![image](https://user-images.githubusercontent.com/100920961/199458979-89f94d16-d9a6-4dca-8805-29af212e3bc2.png)

**Comment by Twigonometry** [comment]
Hi, I believe this is because the markdown files contain examples of Windows shellcode payloads. This also flags on my Windows computer, specifically for files in the [Cereal Writeup](https://github.com/Twigonometry/Cybersecurity-Notes/tree/main/Writeups/Hack%20the%20Box/Boxes/Cereal) directory.

You can add exclusions for these files in Windows Defender which prevents it from scanning them. This has worked for me and Windows no longer flags the repository - otherwise, it will quarantine the markdown files.

There's nothing harmful in the repository, and the IPs that the shellcode point to aren't even public IPs (they are in the 10.10.0.0/24 range, which only works between VPN-connected machines) so rest assured there are no hidden shells :)

If you still get an alert after adding an exclusion for the files in the Cereal directory let me know which specific files are causing the issue and I can see if I can reformat the document so that it doesn't trigger Windows defender, but I feel this would be less useful to people looking to directly copy the commands if using the repository as a cheatsheet.

**Comment by Master-Chiwu** [comment]
I see, thank you for the explanation as to why this may be happening. Your suggestion is actually what I ended up doing to fix this. I was mainly just curious as to why it was happening. Great notes by the way! Thank you for sharing.
